apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: toggle-master
type: Opaque
data:
  DATABASE_URL: <base64_of_rds_connection_string>
  MASTER_KEY: <base64_of_master_key>

---
apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: toggle-master
type: Opaque
data:
  DATABASE_URL: <base64_of_rds_flags_connection_string>

---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-secrets
  namespace: toggle-master
type: Opaque
data:
  DATABASE_URL: <base64_of_rds_targeting_connection_string>

---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: toggle-master
type: Opaque
data:
  REDIS_URL: <base64_of_elasticache_redis_url>

---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: toggle-master
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <base64>
  AWS_SECRET_ACCESS_KEY: <base64>
  AWS_SESSION_TOKEN: <base64>
  AWS_SQS_URL: <base64_of_full_sqs_url>
