apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: toggle-master
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnRvZ2dsZW1hc3RlckB0b2dnbGUtYXV0aC5jbXY2MnM0NDZwaWkudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvYXV0aF9kYj9zc2xtb2RlPXJlcXVpcmU=
  MASTER_KEY: YWRtaW4tc2VjcmV0by0xMjM=

---
apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: toggle-master
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnRvZ2dsZW1hc3RlckB0b2dnbGUtZmxhZy5jbXY2MnM0NDZwaWkudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvZmxhZ3NfZGI/c3NsbW9kZT1yZXF1aXJl

---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-secrets
  namespace: toggle-master
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnRvZ2dsZW1hc3RlckB0b2dnbGUtZmxhZy5jbXY2MnM0NDZwaWkudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvZmxhZ3NfZGI/c3NsbW9kZT1yZXF1aXJl

---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: toggle-master
type: Opaque
data:
  REDIS_URL: cmVkaXM6Ly90b2dnbGUtcmVkaXMuaXN1c2s5Lm5nLjAwMDEudXNlMS5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk=
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vOTQ3MjAwMjgwMDA2L3RvZ2dsZW1hc3Rlcg==
  SERVICE_API_KEY: dG1fa2V5XzU4ZDVhMjUxMDlmYzRkODQyYjhkZTk2N2FhMDIyYmE0ZTcxZDJiYjBlZTJkMTI3MzRmNjVhNDhlMGEyNThkN2M=

---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: toggle-master
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTVaQ01KSVhERVhOR1BOR0g=
  AWS_SECRET_ACCESS_KEY: dUNyOWtwVTV6Y2d1VjhZUlVxUXJwa2I0YUVwWjhVaWVzTEhXM3prVA==
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vOTQ3MjAwMjgwMDA2L3RvZ2dsZW1hc3Rlcg==
