apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
  namespace: toggle-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: auth_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres123
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: auth-db-init

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: toggle-master
spec:
  selector:
    app: postgres-auth
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-flags
  namespace: toggle-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-flags
  template:
    metadata:
      labels:
        app: postgres-flags
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: flags_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: flags-db-init

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-flags
  namespace: toggle-master
spec:
  selector:
    app: postgres-flags
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-targeting
  namespace: toggle-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-targeting
  template:
    metadata:
      labels:
        app: postgres-targeting
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: targeting_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: targeting-db-init

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-targeting
  namespace: toggle-master
spec:
  selector:
    app: postgres-targeting
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
