apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: toggle-master
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres123@postgres-auth:5432/auth_db?sslmode=disable"
  MASTER_KEY: "admin-secreto-123"

---
apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: toggle-master
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres-flags:5432/flags_db"

---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-secrets
  namespace: toggle-master
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres-targeting:5432/targeting_db"

---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: toggle-master
type: Opaque
stringData:
  REDIS_URL: "redis://redis-evaluation:6379"
  AWS_SQS_URL: "http://localstack:4566/000000000000/toggle-queue"
  SERVICE_API_KEY: "tm_key_f2e79a2fd7a8d4c2e1971cf5dd41f51da000c7a9216680a95c9c8300ddafabd6"

---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: toggle-master
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_SESSION_TOKEN: "test"
  AWS_SQS_URL: "http://localstack:4566/000000000000/toggle-queue"
  AWS_ENDPOINT_URL: "http://localstack:4566"
