# Expoe as rotas do auth externamente pelo NLB.
# As rotas reais do app sao /validate e /admin/keys -> nao precisa rewrite.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: auth
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /validate
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8001
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8001
