apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config
  namespace: evaluation
data:
  PORT: "8004"
  # DNS interno dos servicos que o evaluation consulta (fallback do cache)
  FLAG_SERVICE_URL: "http://flag-service.flags.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service.targeting.svc.cluster.local:8003"
  # regiao usada pelo SDK da AWS para publicar na fila SQS
  AWS_REGION: "us-east-1"
