apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-service-scaledobject
  namespace: toggle-master
spec:
  scaleTargetRef:
    name: analytics-service
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.us-east-1.amazonaws.com/947200280006/togglemaster
        queueLength: "5"
        awsRegion: us-east-1
        identityOwner: operator
